openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /tasks:
    get:
      operationId: getTasks
      parameters:
      - name: groupId
        in: query
        schema:
          type: string
          nullable: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postTasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /tasks/{taskId}:
    get:
      operationId: getTasksTaskid
      parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    put:
      operationId: putTasksTaskid
      parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    TaskRequest:
      required:
      - title
      type: object
      properties:
        title:
          type: string
        groupId:
          type: integer
          format: int64
        status:
          type: string
    TaskResponse:
      required:
      - createdAt
      - groupId
      - id
      - status
      - title
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        groupId:
          type: integer
          format: int64
        status:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
