openapi: 3.0.1
info:
  title: Main Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9091"
paths:
  /groups:
    get:
      operationId: getGroups
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: postGroups
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /groups/{groupId}:
    get:
      operationId: getGroupsGroupid
      parameters:
      - name: groupId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    GroupRequest:
      required:
      - description
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    GroupResponse:
      required:
      - createdAt
      - description
      - id
      - title
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
